- basis/compiler/tree/finalization/finalization-docs.factor
- basis/compiler/tree/finalization/finalization.factor
- basis/compiler/tree/late-optimizations/late-optimizations-docs.factor
- basis/compiler/tree/late-optimizations/late-optimizations.factor
- basis/compiler/tree/normalization/normalization-docs.factor
- basis/compiler/tree/normalization/normalization.factor
- basis/compiler/tree/tree-docs.factor
- basis/stack-checker/backend/backend-docs.factor
- basis/stack-checker/backend/backend-tests.factor
- basis/stack-checker/branches/branches-docs.factor
- basis/stack-checker/known-words/known-words-docs.factor
- basis/stack-checker/known-words/known-words-tests.factor
- basis/stack-checker/known-words/known-words.factor
- basis/stack-checker/recursive-state/recursive-state-docs.factor
- basis/stack-checker/state/state-docs.factor
- basis/stack-checker/state/state-tests.factor
- basis/stack-checker/state/state.factor
- basis/stack-checker/values/values-docs.factor
- basis/stack-checker/values/values-tests.factor
- basis/stack-checker/values/values.factor
- basis/stack-checker/visitor/visitor-docs.factor
Here is some docs and tests I've written for the stack-checker hierarchy of vocabs.
> Stack checker docs tests

- basis/compiler/cfg/builder/alien/alien-docs.factor
- basis/compiler/cfg/builder/alien/alien-tests.factor
- basis/compiler/cfg/instructions/instructions-docs.factor
- basis/compiler/cfg/intrinsics/fixnum/fixnum-docs.factor
- basis/compiler/cfg/intrinsics/strings/strings-tests.factor
- basis/compiler/cfg/linear-scan/allocation/state/state-tests.factor
- basis/compiler/cfg/rpo/rpo-docs.factor
- basis/compiler/constants/constants-docs.factor
- basis/compiler/constants/constants.factor
This should fix the 32bit test failures the previous pr caused. The windows build crashes in bootstrap but maybe that's just some stale files or something?
> Gc fixes afl part3

- basis/compiler/cfg/linearization/linearization.factor
- basis/compiler/cfg/ssa/destruction/coalescing/coalescing-docs.factor
- basis/compiler/cfg/ssa/destruction/coalescing/coalescing-tests.factor
- basis/compiler/cfg/ssa/destruction/coalescing/coalescing.factor
- basis/compiler/cfg/ssa/destruction/destruction-docs.factor
- basis/compiler/cfg/ssa/destruction/destruction-tests.factor
- basis/compiler/cfg/ssa/destruction/destruction.factor
- basis/compiler/cfg/ssa/destruction/leaders/leaders-docs.factor
- basis/compiler/cfg/ssa/destruction/leaders/leaders.factor
I think I found the cause of the `project-euler.044` compilation problem. But the committs in this pr should fix it.
> Fix 1345 part2

- basis/stack-checker/known-words/known-words.factor
- core/bootstrap/primitives.factor
- core/memory/memory.factor
- vm/entry_points.cpp
- vm/image.cpp
- vm/primitives.hpp
- vm/vm.hpp
Small fix to the image saving. I noticed that the filesystem path of the image is being saved in it. That's a small privacy hole and redundant so I changed `primitive_save_image` so that those paths aren't saved.
> Save image fix

- basis/windows/dragdrop-listener/authors.txt
- basis/windows/dragdrop-listener/dragdrop-listener-docs.factor
- basis/windows/dragdrop-listener/dragdrop-listener.factor
- basis/windows/dragdrop-listener/platforms.txt
- basis/windows/dragdrop-listener/summary.txt
Hello!
I have brought that vocab from the unmaintained and added some documentation.
It works now.
> windows.dragdrop-listener is revived

- basis/ui/backend/cocoa/views/views.factor
This PR is for unicode-12.1.0, mainly intended to improve the NSTextInputClient support for input other than input methods. For example, if you hold down "e", an input window appears at the "e" position, and you can select its variation.
Unfortunately, there is one big problem with this PR.
Since the code can't get the correct replacementRange argument in  setMarkedText:selectedRange:replacementRange, I use a guess instead.
A subcontract word is like this:
```
:: update-marked-text ( gadget str selectedRange replacementRange -- )
replacementRange location>>  NSNotFound = not     ! [ 
replacementRange length>> NSNotFound = not and [  ! erase this line
gadget editor-caret first
dup gadget editor-line
[ 
replacementRange length>> ! location>>
>codepoint-index
2array gadget set-caret
] [ …
```
> Better support to NSTextInputClient

- basis/command-line/command-line-docs.factor
> Add description of '-help' switch to documentation.

- build.sh
This was causing my issue in #2224
> Redirect when using curl

- build.sh
- vm/Config.windows
- vm/Config.windows.x86.32
- vm/master.hpp
- vm/os-windows.cpp
> Support for MinGW compiler. Need to instal MinGW compiler and runtime.

- README.md
> Added instructions on fetching replace objects for source history

- extra/logic/examples/zebra-short/zebra-short-tests.factor
- extra/logic/examples/zebra-short/zebra-short.factor
- extra/logic/logic-docs.factor
- extra/logic/logic-tests.factor
- extra/logic/logic.factor
- Reduce stack stacking during query processing.
This makes stack overflow less likely and more likely to be answered.
- Added the syntax `LOGIC-PRED:` and `LOGIC-VAR:`.
- Rename `query-n` to `nquery`.
- The speed has increased a little (about 10%).
> Improved `logic`

- extra/rosetta-code/multisplit/authors.txt
- extra/rosetta-code/multisplit/multisplit-tests.factor
- extra/rosetta-code/multisplit/multisplit.factor
- extra/rosetta-code/multisplit/tags.txt
A rosetta-code solution created for https://rosettacode.org/wiki/Multisplit
> rosetta-code.multisplit: new vocab

- extra/sodium/ffi/ffi.factor
- extra/sodium/secure-memory/authors.txt
- extra/sodium/secure-memory/secure-memory-docs.factor
- extra/sodium/secure-memory/secure-memory-tests.factor
- extra/sodium/secure-memory/secure-memory.factor
- extra/sodium/sodium-docs.factor
- extra/sodium/sodium.factor
Extend the libsodium FFI and add a wrapper class for managing sensitive memory blocks (see https://libsodium.gitbook.io/doc/memory_management#guarded-heap-allocations).
> Secure memory

- extra/dns/dns.factor
Fixes an incorrect name for the SRV enum.
Adds parsing of the SRV data.
> Improve DNS SRV record handling

- shell.nix
This adds the shell function `wrapFactor`.  This function is intended to wrap
the result of calling `build.sh` in the shell environment so it can be executed
outside of the nix shell.
Example:
```
$ nix-shell
[nix-shell] $ ./build.sh bootstrap
...build factor vm and image...
[nix-shell] $ wrapFactor .
exit
$ ./factor
```
`wrapFactor` takes the path to the factor root dir as argument, and expects the
binary `factor` and the image file `factor.image` there and uses Nixpkgs'
`makeWrapper` to wrap the `factor` executable in-place with the correct
`LD_LIBRARY_PATH`.  Afterwards, the factor executable can be called outside of
the nix-shell environment.
> shell.nix: supply `wrapFactor` helper to make standalone factor binary

- misc/vim/syntax/factor.vim
i'm bad at titling pull requests edition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/factor/factor/2301)
> fixup! [misc] vim/syntax: Fixups

- core/syntax/syntax-docs.factor
Update the syntax vocab documentation.
> Syntax docs

- misc/vim/syntax/factor.vim
Sorry about the huge delay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/factor/factor/2333)
> misc/vim: fix slot names & tuples.

- extra/raylib/ffi/authors.txt
- extra/raylib/ffi/ffi.factor
Just a bindings update.  Adds some new functions, and changes some minor things to be compatible with the latest Raylib.
> Update Raylib from 2.5 -> 3.5

- Factor.app/Contents/Info.plist
Permit system to identify file extension .factor as text
> Added UTExportedTypeDeclarations to Info.plist

- core/sets/sets.factor
> Add a missing fry

- vm/inline_cache.cpp
I think the two comments need to be swapped to describe the correct thing happening in the code?
> VM: fix comments for inline_cache_jit

- core/sequences/sequences-docs.factor
- core/sequences/sequences-tests.factor
- core/sequences/sequences.factor
Missing member of the pairwise sequence combinator family.
> sequences: Add 2any? combinator

- misc/fuel/factor-mode.el
- misc/fuel/fuel-autodoc.el
- misc/fuel/fuel-autohelp.el
- misc/fuel/fuel-base.el
- misc/fuel/fuel-completion.el
- misc/fuel/fuel-connection.el
- misc/fuel/fuel-debug-uses.el
- misc/fuel/fuel-debug.el
- misc/fuel/fuel-edit.el
- misc/fuel/fuel-eval.el
- misc/fuel/fuel-help.el
- misc/fuel/fuel-listener.el
- misc/fuel/fuel-log.el
- misc/fuel/fuel-markup.el
- misc/fuel/fuel-menu.el
- misc/fuel/fuel-mode.el
- misc/fuel/fuel-popup.el
- misc/fuel/fuel-refactor.el
- misc/fuel/fuel-scaffold.el
- misc/fuel/fuel-stack.el
- misc/fuel/fuel-table.el
- misc/fuel/fuel-tests.el
- misc/fuel/fuel-xref.el
* Use lexical scoping
* Replace deprecated functions
* Fix trivial bugs
> Fuel fixes

- extra/assocs/extras/extras-tests.factor
- extra/assocs/extras/extras.factor
- extra/sequences/abbrev/abbrev.factor
Combine two assocs, specifying a quotation in case there is a value for a
certain key in both.
> assocs.extras: Combinator for merging two assocs

- basis/io/launcher/launcher-docs.factor
- extra/boolean-expr/boolean-expr.factor
- extra/contributors/contributors.factor
- extra/hello-unicode/hello-unicode.factor
- extra/totp/totp.factor
Just some stuff I had lying around.
> Assorted contribs

- extra/boolean-expr/boolean-expr-tests.factor
- extra/boolean-expr/boolean-expr.factor
A fix and some improvements in the `boolean-expr` vocab.
> Boolean expr

- misc/vim/autoload/factor.vim
- misc/vim/plugin/factor.vim
The approach to "vocab:" pathnames is more strict than Factor's, but it also is less likely to infinitely recurse.
> misc/vim: Further improve `:FactorVocab` completion

- vm/image.cpp
Fix as proposed in https://github.com/factor/factor/issues/2580
> Fix issue #2580

- basis/colors/colors-tests.factor
- basis/colors/colors.factor
- extra/color-table/color-table.factor
found basically the same thing in the color-table extra, but this one can
round-trip an alpha channel.
> add color>hex

- basis/xml/errors/errors-docs.factor
> xml.errors: fix typo

- basis/stack-checker/stack-checker.factor
> don't infer things that aren't callable

- basis/persistent/heaps/heaps-docs.factor
> fix typo in heaps-docs.factor

- misc/vim/indent/factor.vim
Create i vim indentation script. { previously misbehaves. : and ; automatically indent/dedent following lines.
> Add vim indent

- basis/promises/promises-docs.factor
- extra/boids/boids.factor
- extra/boids/simulation/simulation.factor
- extra/jamshred/player/player.factor
- extra/jamshred/tunnel/tunnel-tests.factor
- extra/jamshred/tunnel/tunnel.factor
- extra/maze/maze.factor
- extra/path-finding/path-finding-docs.factor
- extra/path-finding/path-finding-tests.factor
- extra/path-finding/path-finding.factor
- extra/pcre/pcre-tests.factor
- extra/project-euler/039/039.factor
- extra/project-euler/070/070.factor
- extra/project-euler/100/100.factor
- extra/project-euler/116/116.factor
- extra/project-euler/151/151.factor
- extra/project-euler/190/190.factor
- extra/raylib/raylib.factor
- extra/rosetta-code/knapsack-unbounded/knapsack-unbounded.factor
- extra/rosetta-code/knapsack/knapsack.factor
- extra/rosetta-code/multiplication-tables/multiplication-tables.factor
- extra/rosetta-code/one-d-cellular/one-d-cellular.factor
- extra/tetris/board/board.factor
- extra/tetris/game/game.factor
- extra/tetris/gl/gl.factor
- extra/tetris/tetromino/tetromino.factor
The spelling should be consistent and follow American English.
> Harmonize spelling

- basis/editors/aquamacs/aquamacs.factor
- basis/editors/aquamacs/authors.txt
(cherry picked from commit 14c0a2f30235c69322a61aa3b4fc992fd09ce70b)
> Added aquamacs editor

- extra/redis/command-writer/command-writer-tests.factor
- extra/redis/command-writer/command-writer.factor
- extra/redis/redis-tests.factor
- extra/redis/redis.factor
Add words to run/load/debug lua scripts
> feature(redis): lua script words

- extra/machine-learning/data-sets/linnerud.rst
> fix typo in data-sets/linnerud.rst

- extra/compression/bzip3/bzip3-docs.factor
- extra/compression/bzip3/bzip3-tests.factor
- extra/compression/bzip3/bzip3.factor
- extra/compression/bzip3/ffi/ffi-docs.factor
- extra/compression/bzip3/ffi/ffi.factor
Adds a vocabulary with bindings to [bzip3](https://github.com/kspalaiologos/bzip3). Plan to merge into extra after some peer reviewing and testing.
> bzip3 compression vocabulary

- extra/help/tour/tour.factor
> help.tour: port and refactor of andrea ferretti's factor tutorial

- basis/peg/peg-docs.factor
Proposal for PEG: documentation.
> peg: Add documentation for PEG:

- basis/peg/ebnf/ebnf.factor
> peg.ebnf: fix typo in ebnf.factor

- basis/english/english.factor
- basis/help/markup/markup.factor
- basis/porter-stemmer/porter-stemmer.factor
Could someone please verify that this change doesn't break anything?
Like bootstraps, lints, etc.
> ascii, unicode: add vowels and vowel?

- LICENSE.txt
Gotta prepare for the next year.
Is there a way to schedule a PR into the future?
> LICENSE.txt: update to 2023

- basis/vocabs/prettyprint/prettyprint.factor
One thing to consider: Does this affect GUI as well?
> Print auto-use message to stderr

- extra/project-euler/463/463-tests.factor
- extra/project-euler/463/463.factor
- extra/project-euler/508/508-tests.factor
- extra/project-euler/508/508.factor
Just two solutions for Project Euler problems 463 and 508. No changes otherwise.
> Project Euler solutions 463 and 508

- factor.entitlements
re. https://discord.com/channels/780615045771821076/786055699271909428/1139352905078558822
> Allow dynamic linker environment variable usage

- factor.entitlements
re. https://discord.com/channels/780615045771821076/786055699271909428/1139403434882236578
> Disable DYLD validation

- extra/sequences/extras/extras-docs.factor
- extra/sequences/extras/extras.factor
Hello! Long-time Factor user and first-time pull requester here. I am very interested in adding documentation to Factor but I figured I'd start small to make sure I'm doing this correctly. This is documentation for the `sift!` word. Please scrutinize extra carefully to make sure I'm not messing anything up.
Old docs: 
New docs:
> Add documentation for sift!

- basis/dns/dns.factor
Just a quick hack to pull `HINFO` records, which must be two pieces of no more than 40 bytes each, length-prefixed.
> parse HINFO records

- basis/x11/xinput2/ffi/ffi.factor
> Fix typo in ffi.factor

- basis/english/english-docs.factor
> fix typo in basis/english/english-docs.factor

- extra/wipe/wipe-docs.factor
ation -> action
Corrected the typo in wipes-docs.factor
> typo fixed in wipe-docs.factor

- CONTRIBUTING.md
I have corrected a few typos in contributing.md
> typo fixed in  CONTRIBUTING.md

- README.md
Reverts factor/factor#2888
There are just as many grammatical issues introduced as this PR "fixes".
Reverting...
> Revert "docs: corrected grammatical errors in README.md"

- basis/json/json-tests.factor
- basis/json/json.factor
> json neg 0 changes

- extra/classes/hierarchy/authors.txt
- extra/classes/hierarchy/hierarchy-docs.factor
- extra/classes/hierarchy/hierarchy-tests.factor
- extra/classes/hierarchy/hierarchy.factor
- extra/classes/hierarchy/summary.txt
- extra/classes/hierarchy/tags.txt
- extra/classes/prettyprinter/authors.txt
- extra/classes/prettyprinter/prettyprinter-docs.factor
- extra/classes/prettyprinter/prettyprinter-tests.factor
- extra/classes/prettyprinter/prettyprinter.factor
- extra/classes/prettyprinter/summary.txt
- extra/classes/prettyprinter/tags.txt
New vocab to display the class hierarchy.
Pls check if the doc is OK, 
The methods :: print-children ( h c i -- ) uses local variable, not sure if use stack operation is possible/desirable.
> added vocab prettyprinter to classes in extra

- basis/math/vectors/ranges/ranges-tests.factor
- basis/math/vectors/ranges/ranges.factor
- basis/math/vectors/vectors.factor
New and improved in its own vocab! (see #2922)
> Add range methods

- basis/ui/gadgets/panes/panes-docs.factor
> docs: Update panes-docs.factor

- basis/calendar/calendar-docs.factor
- basis/calendar/calendar-tests.factor
- basis/calendar/calendar.factor
> calendar: Add sunrise, sunset, solar-noon

- basis/help/tour/tour.factor
> help.tour: fix typo in tour.factor

- extra/gilded-rose/authors.txt
- extra/gilded-rose/gilded-rose-docs.factor
- extra/gilded-rose/gilded-rose.factor
A classic.
Translated from:
https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/main/Delphi/GildedRose.pas
https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/main/Delphi/TextTestFixture.dpr
> gilded-rose: new vocab

- extra/mason/authors.txt
- extra/mason/build/build.factor
- extra/mason/notify/notify.factor
- extra/mason/report/report.factor
- extra/webapps/mason/authors.txt
- extra/webapps/mason/backend/backend.factor
- extra/webapps/mason/status-update/status-update.factor
Stores history of runs and benchmarks in DB.
Next step would be adding functionality to view formatted benchmark results in `webapp.mason`.
> Build infra

- core/sequences/sequences-tests.factor
test push, push-when, push-either
> test(sequences): various push words

- basis/tr/tr-tests.factor
* test translating the last character in tr-test
* use a translation string where the dictionary lengths do not match
> test(tr): improve tests

- core/namespaces/namespaces-tests.factor
> test(namespaces): inc/dec/change/+@

- core/assocs/assocs-tests.factor
delete-at*, ?delete-at, assoc-empty?, assoc=,  assoc-find, subtitute
> test(assoc): various words

- basis/io/pipes/pipes-tests.factor
- basis/io/pipes/pipes.factor
Introduce a word to open two pipes that are connected to each other.
> feature(pipes): <connected-pair>

- basis/msgpack/rpc/rpc-tests.factor
- basis/msgpack/rpc/rpc.factor
- basis/msgpack/rpc/summary.txt
Implemented according to this spec https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md
I haven't yet written the docs because I'm still working on the API. It's at a point where it's usable though.
> feature(msgpack.rpc): introduce vocab for msgpack rpc

- core/destructors/destructors-tests.factor
* Add tests for if-disposed
* Rename disposed? to disposed to follow the disposed protocol and allow calling if-disposed on dispose-dummy
> test(destructors): improvements

- extra/bend/authors.txt
- extra/bend/bend-docs.factor
- extra/bend/bend-tests.factor
- extra/bend/bend.factor
- extra/bend/summary.txt
Adds vocab to extras: "bend", which replicates some language features from the fairly new programming language [bend](https://github.com/HigherOrderCO/bend)
> Add bend vocab

- extra/bend/authors.txt
- extra/bend/bend-docs.factor
- extra/bend/bend-tests.factor
- extra/bend/bend.factor
Following the discussion in discord
> Rework using Johns solution

- basis/help/handbook/handbook.factor
As someone new to Factor, I was initially a bit confused by the various additional stacks used by language internals. As part of learning more about Factor, I've tried to understand the purpose of all of the stacks. I think that would be useful for other people too, so I've added it to a new implementation article in the handbook.
Please read carefully and double-check what I've written here, as I am still quite new to Factor, and I might have something mixed up. 😇
> help.handbook: Add Stacks article with all the stacks used internally

- basis/quoted-printable/rfc2047/authors.txt
- basis/quoted-printable/rfc2047/rfc2047-tests.factor
- basis/quoted-printable/rfc2047/rfc2047.factor
This implements RFC2047 Section 2: https://datatracker.ietf.org/doc/html/rfc2047#section-2
> Add an implementation of RFC2047 strings

- basis/http/client/client.factor
- basis/http/json/json.factor
- basis/mime/types/types-tests.factor
- basis/mime/types/types.factor
- basis/oauth2/oauth2.factor
- extra/backblaze/backblaze.factor
- extra/bitly/bitly.factor
- extra/build-from-source/build-from-source.factor
- extra/discord/discord.factor
- extra/github/github.factor
- extra/google/search/search.factor
- extra/gravatar/gravatar.factor
- extra/hacker-news/hacker-news.factor
- extra/itunes/itunes.factor
- extra/npm/npm.factor
- extra/openai/openai.factor
- extra/reddit/reddit.factor
- extra/scryfall/scryfall.factor
- extra/solr/solr.factor
> Http json refactor

- extra/raylib/raylib.factor
The `TraceLog` function is actually variadic but it just concatenates the text to output, not a big deal. Let me know if it needs to be variadic, and some pointer to how write it, I don't know how to do it
> raylib: fix log functions

- basis/ui/gadgets/buttons/buttons.factor
- basis/ui/gadgets/sliders/sliders.factor
- basis/ui/pens/rounded/rounded.factor
Added in the things I didn't get to in the previous pull request https://github.com/factor/factor/pull/3060 making the drawn slider look more like the previous tiled image slider:
- rounded corner pen (based it off the solid pen)
- small grabber on the slider
- added in a fix for https://github.com/factor/factor/issues/3076
> Add rounded corners pen and slider tweaks

- extra/sequences/extras/extras-docs.factor
- extra/sequences/extras/extras.factor
Closes #3111 
The actual code is quite small. I tried to word the help description as clearly as I could manage, but I'm very open to polish/advice on it.
> sequences.extras: add deep-nth and deep-nth-of

- vm/Config.freebsd
The same flag is set for the linux build.
> Config.freebsd: Unbreak build by adding -fPIC
