basis/locals/locals.factor
basis/locals/parser/parser-tests.factor
basis/locals/parser/parser.factor
basis/locals/types/types-tests.factor
core/parser/parser-docs.factor
core/parser/parser-tests.factor
core/parser/parser.factor

I think this pr should fix #1340. For some reason the `locals` variable got out of sync with the words in the manifest after a restart. I didn't look at that so much because it was easier to just remove `locals` and use `manifest get qualified-vocabs>> last words>>` instead.

Locals fixing

---

basis/compiler/tree/propagation/inlining/inlining-tests.factor
basis/compiler/tree/propagation/known-words/known-words-tests.factor
basis/compiler/tree/propagation/known-words/known-words.factor
basis/compiler/tree/propagation/propagation-tests.factor
basis/compiler/tree/propagation/simple/simple-tests.factor
basis/stack-checker/known-words/known-words.factor
vm/bignum.cpp
vm/bignum.hpp
vm/math.cpp
vm/vm.hpp

Here is a pr I've hacked on to improve propagation for mod type words. It's related #224 and should fix #1230. With the pr:
```factor
IN: [ { integer fixnum } declare /mod fixnum? ] optimized.
[ /i \ t ]
IN: [ { integer } declare 25 /mod 99 * ] optimized.
[ 25 /mod 99 fixnum*fast ]
```
Whereas before:
```factor
IN: [ { integer fixnum } declare /mod fixnum? ] optimized.
[ /mod tag 0 eq? ]
IN: [ { integer } declare 25 /mod 99 * ] optimized.
[
25 /mod 99 over tag 0 eq?
[ fixnum* ] [ fixnum>bignum bignum* ] if
]
```
Sadly, some code becomes worse:
```factor
BEFORE:
IN: [ { bignum bignum } declare mod 100 * ] optimized.
[ bignum-mod 100 bignum* ]
AFTER:
IN: [ { bignum bignum } declare mod 100 * ] optimized.
[
bignum-mod 100 over tag 0 eq?
[ fixnum* ] [ fixnum>bignum bignum* ] if
]
```
But I'm …

Divmod propagation

---

basis/cocoa/cocoa.factor
basis/cocoa/messages/messages.factor
basis/cocoa/touchbar/touchbar.factor
basis/ui/backend/cocoa/views/views.factor

If a method doesn't exist we need to provide a signature so the stack is balanced. This should also allow deploying from macOS versions that do not contain methods to ones that do. This is an alternative to asking a class if it provides a selector.

cocoa: Allow ?-> syntax for methods that might not exist.

---

vm/layouts.hpp

Factor compiles and runs all the tests as normal with this change, but it eliminates the undefined behaviour warnings given to us by ASan. 
Bootstrap took 7 minutes 11 seconds on this machine, which is a little below the average for me.
closes #1919

cast fixes undefined behaviour; closes #1919 in upstream

---

basis/furnace/auth/auth-docs.factor
basis/furnace/auth/providers/couchdb/couchdb-docs.factor

The docs were attempting to reference the CouchDB auth provider, but that fails, because the help vocab didn't include `furnance.auth.couchdb`.
That said, the CouchDB auth provider has such major caveats with it (see the docs) that I think I personally might prefer axing the reference entirely. Thoughts?

furnance.auth: fix documentation

---

basis/documents/documents-docs.factor
basis/documents/documents.factor
basis/ui/backend/cocoa/input-methods/editors/editors.factor
basis/ui/backend/cocoa/input-methods/input-methods.factor
basis/ui/backend/cocoa/views/views.factor
basis/ui/gadgets/editors/editors-docs.factor
basis/ui/gadgets/editors/editors.factor
basis/ui/gadgets/gadgets-docs.factor
basis/ui/gadgets/gadgets.factor
basis/ui/gestures/gestures.factor

This PR provides inline input using input methods in Mac Factor.
To support this internationalization of text input, I have made changes to the editor gadget and the propagation mechanism for key gestures.
Input using Input methods are underlined until their input is confirmed. The editor gadgets changes for this feature are intended for future use with Windows Factor and GTK Factor.
During inline input using an input method, the key gesture is exclusively passed to it.
This PR supports the input of emojis using input methods. Therefore, this PR is for branch unicode-12.1.0.
The Mac Factor's text input protocol changes from NSTextInput to NSTextInputClient.

 Inline input using input methods in Mac Factor

---

basis/core-text/core-text.factor

This PR is for unicode-12.1.0.
It corrects an issue where text containing characters represented as surrogate pairs in UTF-16 cannot display the selection correctly in Mac Factor.

Improved background rendering when selecting text including emojis in Mac Factor

---

basis/compiler/tests/alien.factor
vm/ffi_test.c
vm/ffi_test.def
vm/ffi_test.h

This PR adds tests for passing structures as arguments by value. This became a problem in System V AMD64 ABI.

Tests for System V AMD64 ABI

---

extra/ldcache/ldcache.factor

If '/etc/ld.so.cache' does not contain any old entries
using the 'HeaderOld' struct then it fails with a bad-magic
error before looking for the HeaderNew entries.
My Ubuntu 19.10 system doesn't have any old entries so always
fails here when using 'load-all', which results in the
'extra/llvm' vocab failing due to using 'find-so'.
The fix implemented here is to catch the error and recover from
it by seeking back to the start of the header before looking for
the new header entries.

Fix linux find-so failure if no old ld entries exist

---

basis/math/matrices/matrices-docs.factor
basis/math/matrices/matrices-tests.factor
basis/math/matrices/matrices.factor
extra/math/matrices/extras/extras-docs.factor

closes #2244
- `mnorm` has been renamed to `normalize-matrix`
to reflect what it actually does, which
is normalize a matrix, not find a norm
of a matrix.
- `mnorm` is no longer a word defined here.
- bugfix: previously, `normalize-matrix` found
the supremum of a matrix (`mmax`),
before taking the supremum's absolute
value (`abs`) and dividing the matrix
by it (`m/n`).
for matrices containing only negative
values and 0, the supremum is 0, and
a `div-by-zero` error was thrown.
`normalize-matrix` has been fixed to
first `abs` all the matrix elements,
and then find the supremum and divide,
it also receieved a zero-matrix? guard
for optimization and preventing
`div-by-zero`.
- new alias: `hilbert-schmidt-norm` for
`frobenius-norm`,  to go along with
`math.matrices.extras.<hilbert-matrix>`
and …

math.matrices: fix/rename mnorm, update all norms

---

basis/peg/peg.factor
extra/boyer-moore/boyer-moore-docs.factor
extra/boyer-moore/boyer-moore.factor

Some old uncommitted changes I found lying around: fixing minor typos and using the Factor convention of full-word-names instead of abbreviations like `bc` to look nicer.

fix various typos; cleanup and fully document boyer-moore

---

extra/rosetta-code/multisplit/multisplit.factor

Avoid creating a filtered sequence when all we need is its first element.

rosetta-code.multisplit: reduce memory usage

---

basis/mirrors/mirrors-tests.factor
basis/mirrors/mirrors.factor

`M\ mirror delete-at` and `M\ mirror clear-assoc` have been made to throw a new `mirror-slot-removal` error, because it doesn't make sense to remove a tuple slot, and this behaviour should not have been relied on.
I don't think this breaks anything else but I'm currently loading and testing all vocabs.
closes #1757

mirrors: delete-at and clear-assoc are an error, fix #1757

---

basis/alien/data/data-docs.factor
basis/io/files/windows/windows.factor
basis/literals/literals-docs.factor
basis/windows/kernel32/kernel32.factor
extra/drive-strings/authors.txt
extra/drive-strings/drive-strings.factor
extra/drive-strings/platforms.txt
extra/sodium/secure-memory/secure-memory-docs.factor
extra/sodium/secure-memory/secure-memory.factor
extra/windows/version/authors.txt
extra/windows/version/platforms.txt
extra/windows/version/summary.txt
extra/windows/version/version.factor

Not sure how `windows.version` could be meaningfully unit-tested without adding a file with known VersionInformation resource to the repository.

Some contributions

---

misc/fuel/factor-mode.el

[Imenu](https://www.emacswiki.org/emacs/ImenuMode) is a useful feature in Emacs for jumping to definitions in a given source file. This PR adds support for Imenu tags to `factor-mode`, enabling users to jump to various sorts of definitions in Factor code.

Add imenu tags to factor-mode for Emacs

---

basis/io/standard-paths/unix/unix-tests.factor
basis/io/standard-paths/unix/unix.factor

Fish shell automatically split variables whose name ends in "PATH" into lists,
and uses space as separator for output
Colons force fish to use standard $PATH representation

io.standard-paths: fix standard-login-paths for fish shell

---

basis/compiler/tree/propagation/slots/slots.factor

The last use of `length-accessor?` has been removed in
8e227bc874e356f1e292ab18d1bad1d48966746a, which obsoleted the `length` slot.

compiler.tree.propagation.slots: remove unused word

---

misc/syntax-test.factor
misc/vim/syntax/factor.vim

In which the issues brought up in #2301 are addressed. I really don't see numbers having any more issues from here onwards.
`|:syn-priority|` is respected now, `:syn-skip` & `:syn-keepend` are used when appropriate, newlines don't jank stuff up, comments don't extend match regions, numbers are much more reliable, and stack effect error highlights return.
A feature request has even been sent to Bram.  
https://github.com/vim/vim/issues/872#issuecomment-641025231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/factor/factor/2303)

vim/syntax: Even more fixups.

---

basis/editors/acme/acme-docs.factor
basis/editors/acme/acme-tests.factor
basis/editors/acme/acme.factor
basis/editors/acme/authors.txt
basis/editors/acme/tags.txt

Straightforward editor integration for `acme`[1]. Been using this locally for a little while now, time to clean it up and submit upstream.
[1] http://acme.cat-v.org

Add support for plan9port acme editor

---

basis/compiler/tree/propagation/call-effect/call-effect-tests.factor
basis/compiler/tree/propagation/call-effect/call-effect.factor

Checks if the `slots>>` value-info slot is non-empty before trying to infer
effect from non-literal value-info.
Fixes #2351

compiler.propagation.call-effect: handle class-info-only value-infos

---

basis/ui/images/images.factor
basis/ui/pens/image/image.factor

Allows objects created by `<image>` to be used with `<image-pen>`, using the image-texture-cache.
Example:
```
IN: scratchpad auto-use 1234 { 50 20 } normal-noise-image
IN: scratchpad auto-use <image-pen>
IN: scratchpad auto-use "foo" <label>
IN: scratchpad auto-use swap >>interior
IN: scratchpad auto-use gadget.
```

ui.images: support image tuples as well as image-names

---

basis/models/models-docs.factor
basis/models/models-tests.factor
basis/models/models.factor

`compute-model` can be used to force evaluation of a model.  This is useful during development, but also if you want to use models outside of gadget implementations.
One use I found for me is when using models to compute things like gadget positions, but needing the value before they are grafted.

models: Add word to force recomputation of model values

---

basis/models/arrow/arrow-docs.factor
basis/models/arrow/arrow.factor
basis/models/arrow/smart/smart-docs.factor
basis/models/arrow/smart/smart.factor

Like `<arrow>` and `<smart-arrow>`, but using `?set-model` instead of `set-model`.
This can save computation if a value data-flow model is needed instead of an event data-flow model.

Add <?arrow> and <?smart-arrow> for model updates only when quotation values change

---

core/assocs/assocs-docs.factor
extra/contributors/contributors.factor

What do you think about this?
Without this change the `contributors` vocab is kind of generic and can be used on any git repository, and with this change it's much more specific to the Factor repo. I'm not sure it the change is in line with the original intention behind the vocab.
On the other hand, if it's used on an unrelated repository, there is very little chance that the antialiasing will make any difference at all. It'll essentially be a no-op on almost any other repo in the world.

contributors: merge the known contributor aliases

---

extra/xkcd/xkcd.factor

`random-xkcd.` was broken because the url has changed. I also took a liberty to update urls to use https, as that's what xkcd.com uses by default.
P.S. I haven't looked at factor for a couple of years. I see that it still has regular activity, but the last release was 2.5 years ago. Are there any plans to cut a new release? Any plans for 1.0?

xkcd: fix urls

---

shell.nix

Required for vocabs:
- ogg
- ogg.vorbis
- compression.zlib.ffi
Theoretically, we would need to include every library that has been declared with `LIBRARY:` to make sure all vocabs with ffi work out-of-the box.  This may result in an unacceptable nix closure size though.
Possibly related: #641 
cc @spacefrogg

shell.nix: Add more runtime dependencies, fix opengl dependencies and wrapper

---

basis/models/models.factor
basis/ui/gadgets/gadgets.factor

This allows implementing mixins which then can specify default behavior for
layouting and grafting for their instances.
Specifically concerns these generics:
- `model-changed`
- `layout*`
- `graft*`
- `ungraft*`

Specialize some of gadget's default implementations on object instead

---

basis/compiler/tree/propagation/info/info.factor
basis/compiler/tree/propagation/simple/simple.factor
basis/math/intervals/predicates/predicates-docs.factor
basis/math/intervals/predicates/predicates-tests.factor
basis/math/intervals/predicates/predicates.factor
basis/math/intervals/predicates/summary.txt
core/classes/classes.factor

A `{ class } declare` call will now also refine the value info if the `class`
word has a valid interval in the "declared-interval" property.
This allows certain optimizations during value propagation passes in the
frontend compiler.
For easier usage, a new vocabulary `math.intervals.predicates` is supplied.

Support declaring intervals as well as classes for the optimizing compiler

---

basis/http/http.factor

Fixes #2176
The matching is case sensitive but per RFC 6265 clients should match case-insensitively. When an attribute has uppercase letters, it is interpreted as a cookie name instead. This causes the cookie list to be wrongly parsed, cookies can be torn into multiple ones. When a separated attribute without a value is fed back to a request, it causes the problem mentioned in the issue.
I'm a Factor newbie and I guess this could be written better, without clever deep stack shuffling and forbidden shuffle words.

http: Make parse-set-cookie matching case insensitive

---

shell.nix

This resolves a problem when the wrapped Factor binary is executed with
`GDK_PIXBUF_MODULE_FILE` set to an incompatible version.  This happens if e.g.
Factor is run from within an Emacs that uses newer gdk versions.
Related NixOS issue: https://github.com/NixOS/nixpkgs/issues/54278
In the long run, this should be replaced by a derivation which correctly runs
through all the phases correctly to set up `wrapGAppsHook` correctly.  Even
then, the correct behavior would probably be to have the surrounding
environment (e.g. Emacs) restore the default variable value in it's
sub-environments.

shell.nix: Define gdk pixbuf loaders from build dependencies.

---

basis/compiler/tree/propagation/transforms/transforms.factor
basis/math/intervals/intervals-docs.factor
basis/math/intervals/intervals-tests.factor
basis/math/intervals/intervals.factor

This replicates the `[0,b]` and `[0,b)` words from `math.ranges`.

math.intervals: Add [0,b] and [0,b), use in a couple of places

---

basis/tools/annotations/annotations.factor

Introduces variable `override-annotations`.  If set to `t`, annotating a word
twice will not throw an error, but reset the word and apply the new annotation.
The new word `reset-all` is provided as convenience to reset all known
annotations.

tools.annotations: Optionally re-annotate silently, add reset-all

---

basis/http2/server/server.factor

The basic structure for the HTTP/2 server in factor. Currently, it will check if it should upgrade to HTTP/2, and if not defaults to HTTP/1.1. There are some missing features, including checking for the TLS negotiation, so it just defaults to the insecure case. We ran some manual tests by sending a HTTP/1 request, and it gave the expected response. Unit and integration tests should be added at some point by future contributions. 
Also, when checking the input stream, we would encounter some issues when peeking at the bytes for an upgrade request, so at the moment we have hardcoded it to a false (line 41 of the code currently). If there are any ways to resolve that issue, we can apply them before merging.

HTTP/2 Server Framework

---

basis/io/sockets/secure/openssl/openssl.factor
basis/io/sockets/secure/secure.factor
basis/openssl/libssl/libssl.factor

First attempt at adding support for RFC 7301: Transport Layer Security (TLS) Application-Layer Protocol Negotiation Extension.
Adds necessary bindings to openssl, an additional field to the secure config to store the supported fields, and some additional code to enable alpn for a tls server, provided that the additional field exists and contains items.

TLS server alpn extension support

---

basis/bootstrap/image/primitives/primitives.factor
core/kernel/kernel.factor

I think both-fixnums? can be flushable, even though it can receive mutable inputs.  It will only return `t` for non-mutable inputs though, and `f` for any mutable input.
for `hashcode*`, there is a method which performs a rehash operation, which is not side-effect free.  However, if the result is not needed, it should be possible to optimize out that rehashing.

Make both-fixnums? foldable, hashcode* flushable

---

basis/classes/struct/struct-tests.factor

I change the default value of `margin` in my `.factor-rc`, which breaks some unit tests that include the prettyprinter.
This is just a quick fix for that variable, a more stable fix would probably involve having default values defined for all prettyprinter control variables and set during unit tests.

classes.struct.tests: Set margin prettyprinter control to default

---

basis/tools/test/test-docs.factor
basis/tools/test/test.factor
basis/ui/tools/tools.factor
misc/fuel/fuel-listener.el
misc/fuel/fuel-mode.el

This saves a bit of typing when one uses `F2` and `"long-vocab.name" test "other-vocab" test` a lot during test-driven development. 
Added a default key binding on `Shift-F2` for the UI Tools windows, and the corresponding `fuel` bindings as `C-c M-r` (open to suggestions on this one, not too happy...)

Add command to run unit tests after refreshing

---

core/hashtables/hashtables-tests.factor
core/hashtables/hashtables.factor

Alists have a left-to-right first key occurrence wins access strategy.  This
changes the iteration order when converting an alist via `>hashtable`, so that
the first entry will dominate the resulting assoc.

hashtables: Preserve access semantics for alist >hashtable conversion

---

extra/assocs/extras/extras-tests.factor
extra/assocs/extras/extras.factor

Since `assoc-collapse` uses a clone of the first assoc in the input sequence as
basis for the resulting assoc, this was failing when the first element was `f`.
Change behavior to return a hashtable instead, since this is the
default behavior for `f new-assoc` as well.

assocs.extras: Fix error with assoc-collapse with f as first element

---

extra/assocs/extras/extras-tests.factor
extra/assocs/extras/extras.factor

`assoc-collapse!` is the destructive version of `assoc-collapse`, but takes the
target assoc as extra element.
For `assoc-collapse-as`, the size of resulting assoc is based on the first assoc
in the input sequence.

assocs.extras: Add assoc-collapse! and assoc-collapse-as

---

basis/sequences/windowed/windowed-tests.factor
basis/sequences/windowed/windowed.factor

`{ 1 2 3 4 5 6 7 8 9 } 3 [ >array ] rolling-map ...`
gives
```
{
{ }
{ 1 }
{ 1 2 }
{ 1 2 3 }
{ 2 3 4 }
{ 3 4 5 }
{ 4 5 6 }
{ 5 6 7 }
{ 6 7 8 }
}
```
The first slice is zero elements long, should be one; the last slice doesn't reach the last element of the sequence.
With this change
`{ 1 2 3 4 5 6 7 8 9 } 3 [ >array ] rolling-map ...`
gives
```
{
{ 1 }
{ 1 2 }
{ 1 2 3 }
{ 2 3 4 }
{ 3 4 5 }
{ 4 5 6 }
{ 5 6 7 }
{ 6 7 8 }
{ 7 8 9 }
}
```
which I think is the expected behaviour.

Fix off-by-one error in rolling-map

---

extra/help/lint/coverage/coverage-tests.factor
extra/help/lint/coverage/coverage.factor

fix a regression for `predicate?` words revealed by uses of
`"help" word-prop` over `help:word-help`.
`"help" word-prop` is `f` for `predicate?` words like `array?` and
`zero-matrix?`. a poorly-written comparison in
`M\ word <word-help-coverage>` meant that result was effectively
compared to an empty array { }, instead of just being tested for
emptiness.
additionally, `(word-help)` is introduced to revive the old behaviour of
`help:word-help` before the move to split `$inputs` and `$outputs` in
Help rendering. `(word-help)` provides the actual help content for
words where `"help" word-prop` is `f`, by calling `word-help*`.
closes #2503

help.lint.coverage: fix coverage on predicate? words

---

vm/layouts.hpp

Refactor code to replace defines acting as an enum into a proper (typed) enum.
Refactor code to replace switch-case idiom with proper datastructure to convert to `const char*`
static inline with static local will share static local among (inline) static instances per translation unit

Refactor VM (untyped) defines into (typed) enum

---

basis/ui/tools/listener/listener.factor

avoids having to pop open Keyboard Viewer to hit the virtual F3 key under Touchbar settings that show Control Strip and App Controls only.

put show-error-list in the touchbar

---

extra/fuel/remote/remote.factor

The `integer?` check in `fuel-start-remote-listener` turns the integer into a boolean, causing `<tty-server> start-server` to error
```
Bad store to specialized slot
value t
class integer
``` 
removing the `integer?` check allows the function to work as intended

Allow `fuel-start-remote-listener` to work with a specified port

---

basis/io/files/windows/windows.factor

HOMEPATH and HOMEDRIVE might be set automatically, and HOME can be used to override.
Also HOME is used by several ported commandline utilities to find configuration files.
If the user has set it, he clearly prefers it.

On Windows support HOME environment variable

---

misc/vim/plugin/factor.vim
misc/vim/syntax/factor.vim

I have had some issues using the vim highlighting tools that come with Factor. I tracked those issues down to two causes: wrongly defined commands and lack of a `iskeyword` option set in the syntax definition file. These have been fixed and tested on vim 9.0.135.

Vim highlighting update

---

basis/io/sockets/sockets-tests.factor
basis/io/sockets/sockets.factor

This disambiguates host from port. Another option is to use `.` to separate host from port for ipv6, like some netstats do.

Put brackets around ipv6 addresses in `inet6 present`

---

basis/ui/gadgets/editors/editors-docs.factor
basis/ui/gadgets/editors/editors.factor

Introduces 3 kinds of caret shapes: line, box, filled box
(cherry picked from commit 749ecba7c3e80891109273ff714e993afbe003c0)
#	basis/ui/gadgets/editors/editors.factor

Block caret code

---

core/vocabs/loader/loader.factor

User should be able to use tilde in path.

Add absolute-path to normalize any new root path. E.G. permit ~user

---

extra/contributors/contributors.factor

The previous version was not working correctly.

contributors: fix an alias in the list of contributors

---

.github/workflows/build.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/factor/factor/actions/runs/3154750285/jobs/5132686560#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- build.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github …

ci: add minimum GitHub token permissions for workflow

---

extra/syntax/terse/authors.txt
extra/syntax/terse/terse.factor
misc/fuel/factor-mode.el
misc/fuel/strange-syntax.factor

Addresses #2641; realized that `b>>` and `b<<` conflict with accessors, so changed to using backtick instead of b.

introduce syntax.terse

---

basis/match/match-docs.factor

Match vars are self-evaluating, any mention of get can be confusing.

match: Fix match-cond documentation

---

extra/lint/vocabs/vocabs-docs.factor
extra/lint/vocabs/vocabs-tests.factor
extra/lint/vocabs/vocabs.factor

I've updated `lint.vocabs` to use a less fragile system for parsing. It also makes the parsing process more readable than the long regexp I had. Finally, it should prevent false positives with regards to the `multiline` vocab. Some words have been removed in the refactor process. Additionally, `find-unused.` will show a new import header for the user:

New parser for lint.vocabs

---

core/continuations/continuations.factor

If these words are called with any other `quot` stack effects, they don't compile.

continuations: Clarify ignore-error, ignore-error/f, ignore-errors stack effects

---

basis/shuffle/shuffle.factor

Currently `2reach` is the same as `2pick`. In the sequence `2dup`, `2over`, `2pick`, `2reach`, this should dip one level deeper.

shuffle: Fix 2reach

---

basis/inverse/inverse-tests.factor
basis/inverse/inverse.factor

`2 2 *` and `2 2 swap *` evaluate to `4`. `4 [ 2 * ] undo` evaluates to `2` while `4 [ 2 swap * ] undo` evaluates to `1/2`. Similarly with `+`, where `4 [ 2 swap + ]` evaluates to `-2` instead of `2`.

inverse: Fix swapped + and *

---

extra/sequences/repeating/repeating-tests.factor
extra/sequences/repeating/repeating.factor

The current behavior is confusing:
```
{ 1 2 3 } 2 repeat
{ 1 1 2 2 3 3 }
```
I propose to change it to the following, consistent with the behavior of `cycle`:
```
{ 1 2 3 } 2 repeat
{ 1 2 3 1 2 3 }
{ 1 2 3 } 6 cycle
{ 1 2 3 1 2 3 }
```

sequences.repeating: Fix repeat behaviour

---

README.md

Only project members can clone via the git protocol.

Use https rather than git protocol in download instructions

---

extra/combinators/extras/extras.factor

The stack effect for `4quad@`, `3quad@`, `2quad@`, and `3tri@` were incorrect. I've updated them for the sake of documentation.

combinators.extras: Fix Incorrect Stack Effects

---

extra/brain-flak/authors.txt
extra/brain-flak/brain-flak-docs.factor
extra/brain-flak/brain-flak-tests.factor
extra/brain-flak/brain-flak.factor
extra/brain-flak/summary.txt
extra/brain-flak/tags.txt

During a recent competition I implemented a compiler for the esoteric language [brain-flak](https://esolangs.org/wiki/Brain-Flak) as a Factor vocabulary. Detailed documentation can be found in the vocabulary but here's a quick summary:
Normal word `compile-brain-flak` and syntax word `b-f"` are responsible for compiling brain-flak snippets to Factor. These snippets operate on a `brain-flak` state object which can be constructed from a sequence of numbers. They can also be treated as function on sequences by calling them with `with-brain-flak` wrapper word.
Here's example usage of the vocab:
```factor
: fibonacci-sequence ( n -- array )
1array [ b-f"<>((()))<>{({}[()])<>({}<>)<>(({})<>({}<>))<>}
<>{}{}" ] with-brain-flak ;
10 fibonacci-sequence
{ 1 1 2 3 5 8 13 21 34 55 }
```

Brain-flak vocabulary

---

basis/io/crlf/authors.txt
basis/io/crlf/crlf-docs.factor
basis/io/crlf/crlf-tests.factor
basis/io/crlf/crlf.factor
basis/io/crlf/summary.txt

How do you like the idea of this stream modifier?
Not sure if that's in the spirit of things, to call such a state changer function that updates the context.
I'm open to suggestions about naming of the things in this PR.
The main thing to look at here is the word `use-crlf`, which modifies the current `output-stream` by wrapping it in a class with a custom `stream-nl` method. The latter outputs CRLF.

io.crlf: add use-crlf to support output streams with CRLF for EOL

---

basis/ui/gadgets/tables/tables.factor

this applies the bindings of the arrow keys to ctrl-n/p as well.
I suggest this as I am used to using ctrl-n/p for choosing between completions for vim/kakoune and this allows my muscle memory to not change.

ui.gadgets.tables: adds ctrl-p/n for row selection

---

extra/bson/bson.factor

bson: remove an unnecessary if* call

---

basis/tools/scaffold/scaffold-docs.factor
basis/tools/scaffold/scaffold-tests.factor
basis/tools/scaffold/scaffold.factor

As discussed on discord.
Changes:
- renamed `scaffold-unit-test` and `scaffold-unit-tests` to `read-unit-test` and `read-unit-tests`
- `read-unit-test` now uses `without-limits` for `unparse`
- added a new `scaffold-unit-tests` with expanded interactivity and adding tests directly to the appropriate test file
- documented test scaffolding words
- added unit tests for most test scaffolding words

tools.scaffold: expand and document unit test scaffolding

---

core/ranges/authors.txt
core/ranges/ranges-tests.factor
core/ranges/ranges.factor

Adds specific instance methods to various `sets` generics. This is mostly for better performance, but notable is `intersect` which now returns a new intersection range rather than being converted to vectors first. `intersect` was based off the [Julia implementation](https://github.com/JuliaLang/julia/blob/8e14322b5aa344639dd86bf9eabb84afe831fcba/base/range.jl#L1185) of the same.
Code review, improvements, comments, ideas, problems, all welcome :)

Add set methods to ranges

---

basis/bootstrap/image/image.factor

Due to locals storing their original definition (which includes many otherwise undefined words) under a `lambda` prop, using any local words in core would cause `make-my-image` to crash.
This solves that by properly emitting all the `local?` words it finds. There might be a better place to emit these words, but this seemed the cleanest and most direct. It also seems to work, which is a bonus.
I should note however that I am not very familiar with how images work, and so I am not 100% sure of the implications of this change...
This change was motivated by [this PR](https://github.com/factor/factor/pull/2851) which utilizes a locals word.

Fix for local definitions

---

extra/raylib/raylib.factor
extra/raylib/tags.txt
extra/rlgl/authors.txt
extra/rlgl/demo/authors.txt
extra/rlgl/demo/demo.factor
extra/rlgl/rlgl.factor
extra/rlgl/tags.txt

Resolves #2804 by updating our bindings from `4.5-dev` to `4.5`. It removes functions no longer in raylib, fixes API discrepancies, and adds a new `ARRAY-SLOT`.
Added rlgl bindings, hopefully I didn't miss anything critical. I also ported over one of the demo's using rlgl.

Raylib update bindings and add RLGL bindings

---

extra/raylib/raylib-docs.factor

Turns out there as a stray void causing a failure in `alien.c-types`.

Fix help file

---

core/sequences/sequences-docs.factor

Summary of changes:
- Add `multiline` to `USING:` in order to write [easy-help](https://re.factorcode.org/2023/06/easy-help.html)-style examples.
- Add example to `bounds-check?`:
- Add examples to `clone-like`:
- Add examples to `length`:
- Add examples to `lengthen`:
- Add examples to `like`:
- Add example to `new-sequence`:
- Add example to `nth`:
- Add examples to `set-length`:
- Add examples to `set-nth`:
- Add examples to `sum`:
- Add examples to `sum-lengths`:
- Add example to `virtual-exemplar`:
- Add example to `virtual@`:
John asked for feedback about easy-help. For the most part, it made my job much easier! I couldn't use it everywhere, however, due to two issues:
- Using `{ $snippet "foo" }` inside `{ $examples }` breaks the formatting.
- Creating examples using multiline …

Add examples to generic sequence words that don't have any yet

---

basis/bootstrap/assembler/arm.64.factor

docs: fix typo in basis/bootstrap/assembler/arm.64.factor

---

extra/wordlet/wordlet.factor

Fixed typo in file ./extra/wordlet/wordlet.factor:
reamining -> remaining

Typo fixed in wordlet.factor file

---

basis/opengl/gl/extensions/extensions.factor

suffix appends the "modern" function at the end, which makes it so the old deprecated opengl1 function gets loaded which are not part of the opengl standard anymore and make usage of shader debugger like renderdoc impossible. This fixes it and should also preserve functionality on old hardware.

Fix: correct gl-function loading

---

basis/calendar/calendar-tests.factor
basis/calendar/calendar.factor

Calling `today weekday?` fails with 
```
Generic word year>> does not define a method for the fixnum class.
Dispatching on object: 3
```
Sorry for not including the tests, didn't have the time to figure how to do that yet.

calendar: do not call day-of-week twice in weekday?

---

basis/farkup/farkup.factor

Found a bug while doing some post-processing on the generated XML from Farkup. All tags generated by Farkup share the same `attrs` object. This make modifying this attribute after the fact hazardous.
This PR fixes that.

farkup: revent literal from being modified

---

core/assocs/assocs-docs.factor

Remove out of date note about `zip-as`. Additionally add example with hashtable.

assocs: update docs and give example with hashtable

---

misc/Factor.tmbundle/Syntaxes/Factor.tmLanguage

Hello. This PR adds a new entry to the Factor grammar, which highlights the block comments `/* Comment */` provided by the `multiline` vocabulary. Previously this was not the case, leading to results like this:
I can testify that the new dict works:
(I appended block comments to a random snippet from Rosetta Code in order to quickly test them)
Feel free to test the grammar yourself using [NovaLightshow](https://novalightshow.netlify.app/).
If there are any problems with this PR that I should address, please do not hestitate to inform me. This is my first time contributing to Factor (or to any programming language for that matter). I have read the contribution guidelines and believe that all of the guidelines are accounted for, but I might be mistaken; please let me know if I am.
To …

misc: Add new dict for multiline comments

---

basis/math/combinatorics/combinatorics-tests.factor
basis/math/combinatorics/combinatorics.factor

There is always one 0-permutation, the empty permutation. Previous code produced no permutations for k=0. I removed the check that broke that case.
`load-all \ <k-permutations> usage` tells me that this word isn't used in any definitions.

math.combinatorics: fix <k-permutations> for k=0

---

basis/db/queries/queries.factor

This change permits the use of 'LIKE' statements. The current select-tuples currently uses column = 'text' if test is text. I added a LIKE" which can be used as 
`db [ T{ table  { column LIKE" this" } } select-tuples ] with-db`
This also works with `count-tuples` and the other db.tuple words which use the same underlying code.

Added LIKE" for creating 'WHERE column LIKE' db queries

---

misc/vim/README.md
misc/vim/ftplugin/factor-docs.vim
misc/vim/ftplugin/factor.vim

This adds an optional autopairs functionality.
It also disposes of highlighting overlong lines as errors. Instead I think it would be nicer to use the less glaring mechanism of the colorcolumn option, as the line length limit is often not adhered to.

misc/vim/ftplugin: Add autopairs, colorcolumn instead of margin error

---

basis/grouping/grouping-docs.factor
basis/splitting/monotonic/monotonic-docs.factor

The problem in the `grouping-docs` code example is that the code returns `f` even if the array is fixed to be in decreasing order. The comparison operation is wrong. So, funny enough, it correctly fails, but for the wrong reason.

A couple of documentation fixes

---

extra/grouping/extras/extras-docs.factor

A small change to the `group-by` docs, as it wasn't obvious to me that only consecutive elements are grouped.
I was unable to build (and test) locally, with `algorithm` not found:
```
/usr/bin/clang++ -c -x c++-header -Wall -Wextra -pedantic -DFACTOR_VERSION="0.100" -DFACTOR_GIT_LABEL="heads/feature/group-by-docs-plusplus-163800a44ce3b70b9e1f18f3f21b24b6b8eba4ff" -m64 -O3 -std=c++11 -o vm/master.hpp.gch vm/master.hpp
vm/master.hpp:26:10: fatal error: 'algorithm' file not found
#include <algorithm>
^~~~~~~~~~~
```
So hopefully someone else can test if this renders as I hope it does.

grouping.extras: group-by docs: note consecutive behavior and link collect-by

---

build.sh

Formerly the checks on Linux, whether a required library was found, reported the opposite of the actual result. A correctly configured system would thus report "not found"  for all the X11 and GTK libraries.

Report library existence correctly

---

basis/io/files/windows/windows.factor
vm/factor.cpp

#2204 : use std handles if associated with streams

---

basis/help/markup/markup.factor
basis/help/vocabs/vocabs.factor

The **Vocabulary** section in word-level documentation, and inline vocabulary links in articles that use `$vocab-link`, are split into breadcrumbs so that any hierarchy level of the linked vocabulary can be accessed. Vocabulary-level documentation has similar breadcrumbs added to the **Metadata** section (as `Parents:`) if it has any parent vocabularies.
Examples:
- [breadcrumbed inline link in article](https://ancilla.ancilla.ca/share/t5IIWTca2SA5NdGO1lPD3ADjUJvX21vv5hL9CVFHCKE=/article-alien.endian.html)
- [parent links in vocab docs](https://ancilla.ancilla.ca/share/t5IIWTca2SA5NdGO1lPD3ADjUJvX21vv5hL9CVFHCKE=/vocab-math.functions.private.html)
- [breadcrumbs in word docs](https://ancilla.ancilla.ca/share/t5IIWTca2SA5NdGO1lPD3ADjUJvX21vv5hL9CVFHCKE=/word-assoc-operator%2Cassocs.private. …

Add breadcrumbs to vocabulary links in documentation

---

basis/promises/promises-tests.factor

count number of times the quotation argument is called
demonstrate that failed quotations aren't memoized

test(promises): improve test suite

---

basis/msgpack/msgpack-tests.factor

Reading from an input stream raises an error. This makes it difficult to read all msgpack objects from a stream until exhaustion.
Given that `f` is a valid msgpack value, it is annoying that we can't return false.
I suppose that one simple work around would be to take a quotation that will be called if the eof is reached. Another work around would be to return 2 values on the stack.

test(msgpack): demonstrate eof handling

---

core/slots/slots-tests.factor

* invalid slot attribute
* incompatible initial value
I'm not sure why my tests aren't yielding the errors that I would expect (`bad-slot-attribute`, `bad-initial-value`)

test(parser): slot validation

---

basis/pack/pack-docs.factor
basis/pack/pack.factor
basis/prettyprint/config/config-docs.factor

I'm not even using `pack` myself but I stumbled across it in `terminfo` and decided it could use a manual, especially since the really important part (the format table) is tucked away in pack.private.

Improve `prettyprint.config` documentation; add docs to `pack`

---

extra/variants/variants-tests.factor
extra/variants/variants.factor

Previously, variants without a singleton class as first member which had recursive slots, such as:
```
VARIANT: tree
node { val }
branch { { left tree } { right tree } }
;
```
would throw an error, due to `f` not being a valid initial value for the `tree` slot in `branch`. Now it will find a reasonable initial value (here it would be `T{ node f f }`) to use, allowing this kind of construct.
The tests use `eval` because I was not sure how best to write a test for a potential parse-time error. The added test fails for the previous code, and passes for the new code.

Allow non-singleton as first variant member

---

basis/io/files/info/info-docs.factor
basis/io/files/info/info.factor
extra/terminfo/terminfo-docs.factor
extra/terminfo/terminfo-tests.factor
extra/terminfo/terminfo.factor

tl;dr:
- fix a bug in `io.files.info` needed for terminfo search to work, then fix terminfo search
- use terminfo environment variables to seed the search path
- rework the API to be a bit more flexible and ergonomic
- add support for Curses 5 and Curses 6.1 extensions
- add documentation
- add unit tests for terminfo file decoding
Individual commit messages have more details.

Terminfo overhaul

---

core/assocs/assocs-tests.factor

demonstrate lookups in a stack of assocs where one assoc has keys overriding another

test(assoc): assoc-stack with overriding

---

GNUmakefile

I noticed while attempting some debugging that the debug compiler flags were only set for C files. This adds them to C++ files as well.

build: Apply debug flags to C++ files

---

basis/ui/backend/windows/windows.factor

Hello!
I have noticed that the `paste` word does dummy `GlobalLock`/`GlobalUnlock` without actually using the locked handle. Then I also noticed there is a race condition between check and use.
So, here are the fixes.

Fix Clipboard on Windows

---

basis/opengl/textures/textures-tests.factor
basis/opengl/textures/textures.factor
extra/images/viewer/scaling/scaling-docs.factor
extra/images/viewer/scaling/scaling.factor

Specifically enables multi-texture scaling and adds a gadget that makes the functionality easy to try via something like:
```
USE: images.viewer.scaling "/some/path/to/image.png" load-image <scaling-image-gadget> "scaling-image-test" open-window
```

Bitmap image scaling

---

vm/os-macos.hpp

As a final step for the Mac OS X to macOS rename, this updates the VM OS string to the new value of `macos`. This had to be done separately from the main change so that a boot image could first be prepared that supports both OS strings.

vm: Update OS string for macOS

---

misc/fuel/fuel.el

A package distributed on Melpa must contain a library whose name matches
the name of the package.  This has not been fully enforced in the past.
We alternatively accepted a "fuel-pkg.el" file (with different contents),
but that is about to change.  (Source: I maintain the package used to
create the packages distributed on Melpa.)

FUEL: Add missing fuel.el library

---

basis/tools/deploy/unix/unix.factor

This is a workaround for #3077, maybe could be even considered as a solution.
As per suggestion from @mrjbq7 in [discord](https://discord.com/channels/780615045771821076/786055699271909428/1294306017286426666)

tools.deploy.unix: add .out extension to deployed binaries

---

extra/raylib/raylib-docs.factor
extra/raylib/raylib.factor

Current tests on master fail because of that

raylib: fix linting issues with naming in stack effects

---

core/kernel/kernel-docs.factor

Minor typo fix: `and*` returns the *first* true input, and `or*` returns the *last*.

kernel: Correct docs: or* and*

---

shell.nix

The `gdk-pixbuf` package doesn't use an underscore anymore (and hasn't for a long time).

nixos: update shell.nix

---

core/continuations/continuations-docs.factor
core/continuations/continuations.factor

Try to be consistent:
- resume a continuation
- continue the execution
Add explanation of the continuation lifetime
Add explanation around how continations can be used
ifcc, callcc0, callcc1, Add docs for what happens when the capture quotation returns, not only for when the continuation is resumed (it is actually the normal use case ! when using exception and no exception occurs !)
fix the stack effect of ifcc (inline word so no effect)
fix the docs of the stack effect of ifcc 
fix the docs of with-return and return, reify -> resume

Try to improve continuations docs

---

extra/io/streams/ansi/ansi-docs.factor
extra/io/streams/ansi/ansi-tests.factor
extra/io/streams/ansi/ansi.factor
extra/io/streams/ansi/authors.txt
extra/io/streams/ansi/summary.txt
extra/io/streams/escape-codes/authors.txt
extra/io/streams/escape-codes/escape-codes-docs.factor
extra/io/streams/escape-codes/escape-codes-tests.factor
extra/io/streams/escape-codes/escape-codes.factor
extra/io/streams/escape-codes/summary.txt
extra/terminfo/authors.txt
extra/terminfo/terminfo-docs.factor
extra/terminfo/terminfo.factor

The `terminfo` vocabulary gains convenience words for querying support for specific capabilities: SGR, dim, and 8/256/rgb-colour support.
The `io.streams.escape-codes` vocabulary gets a few extra tests, documentation, and an overview article on formatted TTY output.
The `io.streams.ansi` vocabulary gets documentation, tests, and some significant refactoring, which brings with it support for the dim attribute to get an extra 7 colours on ttys that support it.

terminfo and ANSI-stream improvements

---

extra/combinators/syntax/authors.txt
extra/combinators/syntax/summary.txt
extra/combinators/syntax/syntax-docs.factor
extra/combinators/syntax/syntax-tests.factor
extra/combinators/syntax/syntax.factor

In this pull request, I've added the following syntax words:
`&[ ... | ... ]` : allows for bi, tri and cleave to be written in a much nicer way. For example, `1 &[ 1 + . | 2 + . ]` is equivalent to `1 [ 1 + . ] [ 2 + . ] bi`, and `1 &[ 1 + . | 2 + . | 5 + . | 60 + . ]` is equivalent to `1 { [1 + . ] [ 2 + . ] [ 5 + . ] [ 60 + . ] } cleave`
`*[ ... | ... ]` : allows for bi*, tri*, and spread to be written in a similar syntax to above. For example, `1 2 3 4 *[ 2 + . | 4 - . | 11 * . | 2 - . ]` is equivalent to `1 2 3 4 { [ 2 + . ] [ 4 - . ] [ 11 * . ] [ 2 - . ] } spread`
`N @[ ... ]` : allows for bi@, tri@, and napply to be written in a similar syntax. For example, `2 3 5 7 11 5 @[ 2 * ]` is equivalent to `2 3 5 7 11 [ 2 * ] 5 napply`
The last three syntax words (n&[, n*[, n@[) do similar …

combinators.syntax: added neat syntax for several combinators

---

extra/discord/authors.txt
extra/discord/discord.factor

Currently when a discord bot using `discord` vocab loses internet access it will get a DNS error when attempting to reconnect. This change catches and ignores this error, and adds a wait of a configurable amount of time (2 seconds by default) to every reconnect attempt.
To prevent future deadlocks the reconnect thread now puts a message in the mailbox in the exit handler.
Also includes some minor cleanup like replacing `json-request-headers` with `http-request-json` from the new `http.json` vocab.

discord: handle network disconnects smoother

---

basis/help/tour/tour.factor

This is mostly just a few typos/missing words in the Guided Tour help section. The one vaguely significant change is a change from a `$snippet` to a `$code`, aimed at allowing for sending the sentence to the listener.

help.tour: fix some typos/grammar

---

core/hashtables/wrapped/wrapped-docs.factor

The methods `>alist` and `>keys` of `wrapped-hashtable` depend on the key wrapper implementing access to the original key via `underlying>>`.  Document this.

hashtables.wrapped: Document key wrapper requiring specific slot

---

basis/persistent/hashtables/hashtables.factor

If these are not loaded, methods are undefined when actually using persistent hashtables.
These were removed during a cleanup in 6aa8f640c8b2c268c27e72ffc5991c864fafed19, i suspect that was because no undefined words from these vocabs are actually referenced directly.

persistent.hashtables: Use vocabularies that define needed behavior

---

shell.nix

This is a small update, renaming the helper to wrap a factor image/executable in NixOS to the name that is used in the nixpkgs repo itself.

shell.nix: Update package name, use same naming for helper as Nixpkgs

---

basis/mime/multipart/multipart.factor

The changed part of `dump-until-separator` is supposed to write the rest of the buffer leaving only as many bytes as the length of the separator (minus 1) to ensure proper detection of a separator that falls on the buffer-size boundary. Currently it improperly calculates the index to split the buffer at to `lenght(separator) - length(buffer) - 1` instead of `length(buffer) - length(separator) - 1`. This is a fix to that issue.

mime.multipart: fix buffer refill behavior

---

build.sh
vm/platform.hpp

This fixes build errors on DragonFlyBSD because DragonFly doesn't call itself FreeBSD, even though that's its base.

build.sh, platform.hpp: support for DragonFlyBSD
